config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'gmaps/index'
  get     'login', to: 'sessions#new'
  post    'login', to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'
  delete  'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'contact', to: 'contacts#new'
  get 'portfolio', to: 'case_studies#index'
  get 'case-studies/hr'
  get 'industries/healthcare'
  get 'industries/retail'
  get 'industries/digital'
  get 'industries/logistics'
  get 'industries/travel'
  get 'industries/media'
  get 'skills', to: 'skills#index'
  get 'skills/laravel'
  get 'skills/codeigniter'
  get 'skills/symfony'
  get 'skills/ror'
  get 'skills/reactnative'
  get 'skills/reactjs'
  get 'skills/vuejs'
  get 'skills/android'
  get 'skills/nodejs'
  get 'skills/swift'
  get 'skills/ios'
  get 'skills/angularjs'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/application-development', to: 'static_pages#application_development'
  get '/application-maintenance', to: 'static_pages#application_maintenance'
  get '/application-modernization', to: 'static_pages#application_modernization'
  get '/testing-qa', to: 'static_pages#testing_qa'
  get '/co-development', to: 'static_pages#co_development'
  get '/dedicated-development-teams', to: 'static_pages#dedicated_development_teams'
  get '/geocoder4rails', to: 'gmaps#geocoder4rails'

  get '/twilios/send_test', to: 'twilios#send_test'
  post '/twilio-api/recv-sms', to: 'twilios#recv_sms'
  get '/twilio-api/recv-sms-test', to: 'twilios#recv_sms_test'

  get '/twilio-api', to: 'twilio_histories#iframe'
  get '/twilio_histories/:id/delete', to: 'twilio_histories#destroy'


  resources :microposts
  resources :users
  resources :contacts
  resources :gmaps
  resources :twilio_histories
  resources :messages
  resources :tracks
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update, :show]


  #root "static_pages#home"
  root "static_pages#home"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<style>
  .header_new .menu_new li .sub_menu_new .hire_devl li a.ionic,
  .header_new .menu_new li .sub_menu_new .hire_devl li:hover a.ionic {
    background-position: 0 -2206px;
    border-bottom: 0 solid #d7d7d7;
  }

  .site-slogan {
    color: white;
    font-size: 20pt !important;
  }

  @media screen and (max-width: 1280px) {
    .site-slogan {
      font-size: 15pt !important;
    }
  }

  @media screen and (max-width: 1024px) {
    .site-slogan {
      font-size: 10pt !important;
    }
  }

  @media screen and (max-width: 765px) {
    .site-slogan {
      font-size: 10pt !important;
      line-height: 40px !important;
      display: block !important;
      /* float: left; */
      height: 40px !important;
      float: none!important;
    }
    .header_new .menu_new .hire_dvl_list{
      margin-left: 0px;
    }
    .header_new .menu_new li .sub_menu_new .sub-menu-list li a,
    .header_new .menu_new li .sub_menu_new .hire_devl li a{
      background-position-x: -10px!important;
    }
    .header_new .menu_new li .sub_menu_new .hire_devl li .laravel,
    .header_new .menu_new li .sub_menu_new .hire_devl li .ror
    {
      background-position-x: 7px!important;

    }
    .header_new .menu_new{
      left: 90px!important;
    }

    body {
      margin-top: 300px !important;
    }
  }

</style>
<script>

    $(function () {
        $(window).scroll(function () {
            if ($(this).scrollTop() > 500) {
                $('.logo img').attr('src', '/logo.png?v1');
            }
            if ($(this).scrollTop() < 500) {
                $('.logo img').attr('src', '/logo.png?v1');
            }
        });
    });

</script>
<header class="header_new navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-3 col-lg-3 col-md-3">
        <a href="/" class="logo" title="WebMobile"><img src="/logo.png"
           width="100%" org-src="common/images/VC-Log-1.png?v1" alt="Dedicated - Logo"/></a>
        <span class="mob_icon2"></span>
      </div>
      <div class="col-xs-12 col-sm-9 col-lg-9 col-md-9">
        <span class="site-slogan" style="color: white;font-size: 20pt;line-height: 70px;
            float: left; height: 60px;">
          Ray Pride's demo app
        </span>
        <nav>
          <ul class="nav navbar-nav navbar-right" style="margin-top: 18px;">
            <li><%=link_to 'Help', help_path %></li>
            <!--li><%=link_to 'About', about_path %></li-->
            <% unless logged_in2? %>
              <li><%=link_to 'Signup', signup_path %></li>
              <li><%=link_to 'Log in', login_path %></li>
            <% else %>
              <li><%=link_to 'Inbox', messages_path %></li>
              <li><%=link_to 'Log out', logout_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <p>&nbsp;</p>
      <% flash.each do |message_type, message| %>
        <div onclick="this.style.display='none'"
          class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

      <% render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>